name: Momo-Store-Application

env:
  VERSION: 1.0.${{ github.sha }}

on:
  push:
    paths:
      - 'momo-store-application/**'
      - '.github/workflows/momo-store-application.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build Momo Store Docker Images
        run: |
          cd momo-store-application/backend
          docker build . --file Dockerfile --tag momo-store-backend:${{ env.VERSION }}

      - name: Push Docker image to registry
        run: |
          echo $LOGIN_DOCKER_REGISTRY
          echo $SERVICE_TOKEN_GITHUB | docker login ghcr.io -u $LOGIN_DOCKER_REGISTRY --password-stdin
          docker push ghcr.io/redolf/momo-store-backend:${{ env.VERSION }}
