name: Momo-Store-Application

env:
  VERSION: 1.0.${{ github.sha }}

on:
  push:
    paths:
      - 'momo-store-application/**'
      - '.github/workflows/momo-store-application.yml'

jobs:

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Run code linter
        run: go vet ./...

  build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Momo Store Docker Images
        run: |
          cd momo-store-application/backend
          docker build . --file Dockerfile --tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}
          echo ${{ env.VERSION }}
          docker images

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.SERVICE_TOKEN_GITHUB }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
          docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone repository
#         uses: actions/checkout@v4
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ secrets.USERNAME_GITHUB }}
#           password: ${{ secrets.SERVICE_TOKEN_GITHUB }}
#       - name: Change dir Backend
#         run: |
#           cd momo-store-application/backend
#           pwd
#           ls -la
#           cat Dockerfile
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: |
#             user/app:latest
#             user/app:1.0.0            
#       - name: Push image to GHCR
#         run: |
#           docker buildx imagetools create \
#             --tag ghcr.io/user/app:latest \
#             --tag ghcr.io/user/app:1.0.0 \
#             user/app:latest
