name: Momo-Store-Application

env:
  VERSION: 1.0.${{ github.sha }}

on:
  push:
    paths:
      - 'momo-store-application/**'
      - '.github/workflows/momo-store-application.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build Momo Store Docker Images
        run: |
          cd momo-store-application/backend
          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          # docker build --platform linux/amd64,linux/arm64 --tag backend:latest --tag backend:{{ github.sha }} .
          # docker buildx imagetools inspect backend:latest
          # docker buildx imagetools inspect backend:{{ github.sha }}
          ls -la
