name: Momo-Store-Backend

env:
  VERSION: 1.0.${{ github.sha }}

on:
  push:
    paths:
      - 'momo-store-application/backend/**'
      - '.github/workflows/momo-store-backend.yml'



jobs:

  build:
    defaults:
      run:
        working-directory: ./momo-store-application/backend
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Momo Store Backend Docker Images
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}
          echo ${{ env.VERSION }}
          docker images

      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.SERVICE_TOKEN_GITHUB }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
          docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}

  test:
    defaults:
      run:
        working-directory: ./momo-store-application/backend
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
      
      - name: Install dependencies
        run: |
          cd ./cmd/api
          go get .

      - name: Test with the Go CLI
        run: go test -v ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Release Momo Store Backend Docker Images
        run: |
          echo ${{ secrets.SERVICE_TOKEN_GITHUB }} | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin
          docker pull ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }}
          docker tag ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:${{ env.VERSION }} ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:latest
          docker push ghcr.io/${{ secrets.USERNAME_GITHUB }}/momo-store-backend:latest
